### ISSUE TITLE
new uhd compile failed

### ISSUE THREAD

**Issue by askyst** [garverp/gr-analysis#7]
https://github.com/EttusResearch/uhd/commit/ba04a5f652e6eec19865a67f163a5dc1f7294e45
According to this commit, "utils: Replaced uhd::atomic_uint32_t with std::atomic". So   uhd::atomic_uint32_t does not exist anymore. Compiling specrec will always fail. Please update the code of specrec.cpp accordingly.

**Comment by berttheengineer** [comment]
I went to gr-analysis/apps/record/specrec.cpp and modified the following: change line 62 from "uhd::atomic_uint32_t num_elements;" to "std::atomic<uint32_t> num_elements;" , change line 345 from "num_elements.inc();" to "num_elements++", and change line 417 from "boost::uint32_t cur_cb_size= num_elements.read();" to "boost::uint32_t cur_cb_size= num_elements;". This worked for me, hope it helps. Sorry for poor formatting, I just joined

**Comment by garverp** [comment]
Thanks for sharing the solution! Can you submit a pull request with these changes? 

Also, what version of UHD did you verify this fix with?

**Comment by berttheengineer** [comment]
Sorry I've been traveling, I've never done a pull request before (never used github before this summer). If you could tell me the steps involved or link me to directions that be great. I'll check on the UHD version when I have access to the machine to verify but I'm fairly certain it was the most recent version

**Comment by garverp** [comment]
Closing, should be fixed by PR #8
